/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Links = {
  _id: string;
  _type: "links";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  social_links?: Array<{
    enabled?: boolean;
    url?: string;
    platform?: "instagram" | "linkedin" | "tiktok" | "youtube";
    _type: "social_link";
    _key: string;
  }>;
  other_links?: Array<{
    title?: string;
    description?: string;
    url?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "other_link";
    _key: string;
  }>;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Trusted_byReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "trusted_by";
};

export type Services = {
  _id: string;
  _type: "services";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  subheading?: string;
  services?: Array<{
    title?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    body?: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }>;
    _type: "service";
    _key: string;
  }>;
  show_trusted_by?: boolean;
  trusted_by?: Trusted_byReference;
};

export type Bio = {
  _id: string;
  _type: "bio";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading?: string;
  subheading?: string;
  letter?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  quote?: string;
  bio_heading?: string;
  pro_bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  certs_heading?: string;
  certs_pre?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  certifications?: Array<{
    title?: string;
    description?: string;
    _type: "certification";
    _key: string;
  }>;
  certs_post?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero_heading?: string;
  hero_subheading?: string;
  hero_cta?: string;
  hero_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  show_WBH_hero?: boolean;
  WBH_subheading?: string;
  WBH_CTA?: string;
  bio_snippet?: string;
  bio_CTA?: string;
  bio_image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  testimonials?: Array<{
    quote?: string;
    person?: string;
    _type: "testimonial";
    _key: string;
  }>;
  collab_heading?: string;
  collaborations?: Array<{
    title?: string;
    subtitle?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    platform?: "spotify" | "youtube" | "instagram";
    _type: "collaboration";
    _key: string;
  }>;
  services?: Array<{
    title?: string;
    body?: string;
    cta?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "service";
    _key: string;
  }>;
  show_trusted_by?: boolean;
  trusted_by?: Trusted_byReference;
};

export type Trusted_by = {
  _id: string;
  _type: "trusted_by";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  companies?: Array<{
    name?: string;
    image?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "company";
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Links
  | SanityImageCrop
  | SanityImageHotspot
  | Trusted_byReference
  | Services
  | Bio
  | Homepage
  | Trusted_by
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: ../src/lib/loaders.ts
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepage"][0] {    "hero": {      "heading": hero_heading,      "subheading": hero_subheading,      "imageUrl": hero_image.asset->url,      "cta": hero_cta    },    "wbh": {      "show": show_WBH_hero,      "subheading": WBH_subheading,      "cta": WBH_CTA    },    "bio": {      "snippet": bio_snippet,      "cta": bio_CTA,      "imageUrl": bio_image.asset->url    },    "testimonials": testimonials[]{quote, person},    "collabs": {      "heading": collab_heading,      "collaborations": collaborations[]{        title,        subtitle,        "imageUrl": image.asset->url,        platform      }    },    "services": services[]{      title,      body,      cta,      "imageUrl": image.asset->url    },    "trustedBy": {      "show": show_trusted_by,      "companies": trusted_by->companies[]{        name,        "logoUrl": image.asset->url      }    }  }
export type HOMEPAGE_QUERY_RESULT = {
  hero: {
    heading: string | null;
    subheading: string | null;
    imageUrl: string | null;
    cta: string | null;
  };
  wbh: {
    show: boolean | null;
    subheading: string | null;
    cta: string | null;
  };
  bio: {
    snippet: string | null;
    cta: string | null;
    imageUrl: string | null;
  };
  testimonials: Array<{
    quote: string | null;
    person: string | null;
  }> | null;
  collabs: {
    heading: string | null;
    collaborations: Array<{
      title: string | null;
      subtitle: string | null;
      imageUrl: string | null;
      platform: "instagram" | "spotify" | "youtube" | null;
    }> | null;
  };
  services: Array<{
    title: string | null;
    body: string | null;
    cta: string | null;
    imageUrl: string | null;
  }> | null;
  trustedBy: {
    show: boolean | null;
    companies: Array<{
      name: string | null;
      logoUrl: string | null;
    }> | null;
  };
} | null;

// Source: ../src/lib/loaders.ts
// Variable: BIO_QUERY
// Query: *[_type == "bio"][0] {    "hero": {      heading,      subheading    },    letter,    quote,    "proBio": {      "heading": bio_heading,      "body": pro_bio    },    "certs": {      "heading": certs_heading,      "preText": certs_pre,      certifications[]{title, description},      "postText": certs_post    }  }
export type BIO_QUERY_RESULT = {
  hero: {
    heading: string | null;
    subheading: string | null;
  };
  letter: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  quote: string | null;
  proBio: {
    heading: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  };
  certs: {
    heading: string | null;
    preText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    certifications: Array<{
      title: string | null;
      description: string | null;
    }> | null;
    postText: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
  };
} | null;

// Source: ../src/lib/loaders.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "services"][0] {    "hero": {      heading,      subheading    },    services[]{      title,      body,      "imageUrl": image.asset->url    },    "trustedBy": {      "show": show_trusted_by,      "companies": trusted_by->companies[]{        name,        "logoUrl": image.asset->url      }    }  }
export type SERVICES_QUERY_RESULT = {
  hero: {
    heading: string | null;
    subheading: string | null;
  };
  services: Array<{
    title: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    imageUrl: string | null;
  }> | null;
  trustedBy: {
    show: boolean | null;
    companies: Array<{
      name: string | null;
      logoUrl: string | null;
    }> | null;
  };
} | null;

// Source: ../src/lib/loaders.ts
// Variable: LINKS_QUERY
// Query: *[_type == "links"][0] {    "social": social_links[]{      platform,      url    },    "other": other_links[]{      title,      description,      url,      "imageUrl": image.asset->url    }  }
export type LINKS_QUERY_RESULT = {
  social: Array<{
    platform: "instagram" | "linkedin" | "tiktok" | "youtube" | null;
    url: string | null;
  }> | null;
  other: Array<{
    title: string | null;
    description: string | null;
    url: string | null;
    imageUrl: string | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "homepage"][0] {\n    "hero": {\n      "heading": hero_heading,\n      "subheading": hero_subheading,\n      "imageUrl": hero_image.asset->url,\n      "cta": hero_cta\n    },\n\n    "wbh": {\n      "show": show_WBH_hero,\n      "subheading": WBH_subheading,\n      "cta": WBH_CTA\n    },\n\n    "bio": {\n      "snippet": bio_snippet,\n      "cta": bio_CTA,\n      "imageUrl": bio_image.asset->url\n    },\n\n    "testimonials": testimonials[]{quote, person},\n\n    "collabs": {\n      "heading": collab_heading,\n      "collaborations": collaborations[]{\n        title,\n        subtitle,\n        "imageUrl": image.asset->url,\n        platform\n      }\n    },\n\n    "services": services[]{\n      title,\n      body,\n      cta,\n      "imageUrl": image.asset->url\n    },\n\n    "trustedBy": {\n      "show": show_trusted_by,\n      "companies": trusted_by->companies[]{\n        name,\n        "logoUrl": image.asset->url\n      }\n    }\n  }': HOMEPAGE_QUERY_RESULT;
    '*[_type == "bio"][0] {\n    "hero": {\n      heading,\n      subheading\n    },\n\n    letter,\n\n    quote,\n\n    "proBio": {\n      "heading": bio_heading,\n      "body": pro_bio\n    },\n\n    "certs": {\n      "heading": certs_heading,\n      "preText": certs_pre,\n      certifications[]{title, description},\n      "postText": certs_post\n    }\n  }': BIO_QUERY_RESULT;
    '*[_type == "services"][0] {\n    "hero": {\n      heading,\n      subheading\n    },\n\n    services[]{\n      title,\n      body,\n      "imageUrl": image.asset->url\n    },\n\n    "trustedBy": {\n      "show": show_trusted_by,\n      "companies": trusted_by->companies[]{\n        name,\n        "logoUrl": image.asset->url\n      }\n    }\n  }': SERVICES_QUERY_RESULT;
    '*[_type == "links"][0] {\n    "social": social_links[]{\n      platform,\n      url\n    },\n\n    "other": other_links[]{\n      title,\n      description,\n      url,\n      "imageUrl": image.asset->url\n    }\n  }': LINKS_QUERY_RESULT;
  }
}
